version: '3'
services:
  flaskapp:
    build: .
    env_file:
      - env_file
    volumes:
      - .:/opt/services/flaskapp/src
    networks:
      - db_network
      - web_network
    depends_on:
      - db
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
